spring.application.name=TicketingSystem_Maven
server.port=8881

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.password=test
spring.datasource.port=9991
spring.datasource.url=jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=test
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
